In [1]:
import numpy as np

In [2]:
first = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
second = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
np.concatenate((first, second))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [5]:
np.concatenate((first, second), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [6]:
np.concatenate((np.array([1, 2, 3, 4]), np.array([5, 6, 7, 8])))

array([1, 2, 3, 4, 5, 6, 7, 8])