In [28]:
import numpy as np

## 1. Calculating Total Revenue

In [29]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [30]:
quantities = np.array([10, 5, 8, 12, 3])
quantities

array([10,  5,  8, 12,  3])

In [31]:
revenue_per_product = prices * quantities
revenue_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [32]:
total_revenue = np.sum(revenue_per_product)
total_revenue

664.62

## 2. Analyzing Blog Post Stats

In [33]:
views = np.array([1000, 500, 800, 1200, 300, 600])
views

array([1000,  500,  800, 1200,  300,  600])

In [34]:
max_views = np.max(views)
max_views

1200

In [35]:
min_views = np.min(views)
min_views

300

In [36]:
average_views = round(np.mean(views), 3)
average_views

733.333

In [37]:
total_views = np.sum(views)
total_views

4400

## 3. Splitting Order into Batches

In [38]:
order_ids = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])

In [39]:
batches = np.split(order_ids, 4)
batches

[array([1001, 1002]),
 array([1003, 1004]),
 array([1005, 1006]),
 array([1007, 1008])]

In [40]:
for i, batch in enumerate(batches):
    print("Batch number: ", i)
    print("First emenet in the batch: ", batch[0])
    print("Secont emenet in the batch: ", batch[1])
    print("")

Batch number:  0
First emenet in the batch:  1001
Secont emenet in the batch:  1002

Batch number:  1
First emenet in the batch:  1003
Secont emenet in the batch:  1004

Batch number:  2
First emenet in the batch:  1005
Secont emenet in the batch:  1006

Batch number:  3
First emenet in the batch:  1007
Secont emenet in the batch:  1008



## 4. Categorizing Product Ratings

In [41]:
ratings = np.array([4.5, 3.2, 2.8, 5.0, 4.1, 3.9, 2.5, 4.7])
ratings

array([4.5, 3.2, 2.8, 5. , 4.1, 3.9, 2.5, 4.7])

In [42]:
positive_ratings = ratings[ratings >= 4.0]
positive_ratings

array([4.5, 5. , 4.1, 4.7])

In [43]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([3.2, 2.8, 3.9, 2.5])

## 5. Calculate Total & Avarage Quantities Sold

In [44]:
# Each colum is specific product (we have 4 products)
# Each row is specific order (we have 2 orders)
order_quantities = np.array([[5, 3, 2, 7], [10, 6, 3, 9]])
order_quantities

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

In [45]:
# Quantities of the sales per product
total_quantities_sold = np.sum(order_quantities, axis=0)
total_quantities_sold

array([15,  9,  5, 16])

In [46]:
# Quantities of the sales per order
total_quantities_sold = np.sum(order_quantities, axis=0)
total_quantities_sold

array([15,  9,  5, 16])

In [47]:
avarage_quantities_sold = np.mean(order_quantities, axis=1)
avarage_quantities_sold

array([4.25, 7.  ])

## 6. Calculate Average Product Rating and Maximum Rating per Category

In [48]:
# Each row is one product
# Each row is rated in 4 categories
product_ratings = np.array([
    [4.5, 3.2, 2.5, 5.0],
    [4.3, 3.8, 1.0, 4.8],
    [2.0, 3.6, 4.7, 0.5]
])
product_ratings

array([[4.5, 3.2, 2.5, 5. ],
       [4.3, 3.8, 1. , 4.8],
       [2. , 3.6, 4.7, 0.5]])

In [49]:
# Average rating in each category
avarage_rating_per_category = np.mean(product_ratings, axis=0)
avarage_rating_per_category

array([3.6       , 3.53333333, 2.73333333, 3.43333333])

In [50]:
# Max rating in each category
max_rating_per_category = np.max(product_ratings, axis=0)
max_rating_per_category

array([4.5, 3.8, 4.7, 5. ])

## 7. Generation of The Sample Stock Data

In [51]:
companies = ['Google', 'Microsoft', 'Apple']
days = ['Monday 1 April', 'Tuesday 2 April']
price_types = ['Open', 'Close', 'High', 'Low']

In [52]:
# Shape will be (3, 2, 4)
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [53]:
stock_prices.shape

(3, 2, 4)

In [54]:
for i, company in enumerate(companies):
    print(f'Stock prices for the {company}:')

    for j, day in enumerate(days):
        print(f'Day: {day}')

        for k, price_type in enumerate(price_types):
            print(f'{price_type} Price: {stock_prices[i, j, k]}')
        print('')
    print('')

Stock prices for the Google:
Day: Monday 1 April
Open Price: 0.417
Close Price: 0.72
High Price: 0.0
Low Price: 0.302

Day: Tuesday 2 April
Open Price: 0.147
Close Price: 0.092
High Price: 0.186
Low Price: 0.346


Stock prices for the Microsoft:
Day: Monday 1 April
Open Price: 0.397
Close Price: 0.539
High Price: 0.419
Low Price: 0.685

Day: Tuesday 2 April
Open Price: 0.204
Close Price: 0.878
High Price: 0.027
Low Price: 0.67


Stock prices for the Apple:
Day: Monday 1 April
Open Price: 0.417
Close Price: 0.559
High Price: 0.14
Low Price: 0.198

Day: Tuesday 2 April
Open Price: 0.801
Close Price: 0.968
High Price: 0.313
Low Price: 0.692


