In [2]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(10, 15)

array([10, 11, 12, 13, 14])

In [5]:
np.arange(10, 15, 2)

array([10, 12, 14])

In [7]:
np.arange(start=10, stop=15, step=2)

array([10, 12, 14])

In [13]:
np.arange(30).reshape([3, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [18]:
np.arange(30).reshape([3, 10]).reshape([3, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [19]:
np.arange(20).reshape([2, 2, 5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [21]:
np.random.seed(10)
np.random.random((10, )).reshape((2, 5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981]])