In [2]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(10, 15)

array([10, 11, 12, 13, 14])

In [5]:
np.arange(10, 15, 2)

array([10, 12, 14])

In [7]:
np.arange(start=10, stop=15, step=2)

array([10, 12, 14])

In [13]:
np.arange(30).reshape([3, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [18]:
np.arange(30).reshape([3, 10]).reshape([3, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [19]:
np.arange(20).reshape([2, 2, 5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [21]:
np.random.seed(10)
np.random.random((10, )).reshape((2, 5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981]])

In [22]:
np.random.seed(10)
np.random.randint(50, 80, (4, 3, 3))

array([[[59, 79, 54],
        [65, 50, 67],
        [77, 78, 75]],

       [[79, 66, 79],
        [67, 76, 58],
        [59, 50, 60]],

       [[58, 72, 54],
        [69, 66, 54],
        [65, 61, 72]],

       [[74, 61, 76],
        [51, 58, 54],
        [64, 67, 69]]], dtype=int32)

In [24]:
np.random.randint(50, 80, (4, 3, 3)).flatten()

array([61, 78, 51, 70, 76, 50, 74, 62, 55, 54, 57, 74, 74, 68, 62, 72, 52,
       58, 65, 63, 74, 65, 79, 56, 72, 71, 60, 72, 61, 66, 62, 78, 50, 72,
       75, 67], dtype=int32)

In [27]:
np.arange(30).reshape((3, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])