In [1]:
import numpy as np

In [4]:
first = np.array([[1, 2, 3], [4, 5, 6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
first.ndim

2

In [8]:
second = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
first + second

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [10]:
first + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [12]:
first - 1

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
first * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
first / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])