In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(10, 15)

array([10, 11, 12, 13, 14])

In [4]:
np.arange(10, 15, 2)

array([10, 12, 14])

In [5]:
np.arange(start=10, stop=15, step=2)

array([10, 12, 14])

In [6]:
np.arange(30).reshape([3, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [7]:
np.arange(30).reshape([3, 10]).reshape([3, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [8]:
np.arange(20).reshape([2, 2, 5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [9]:
np.random.seed(10)
np.random.random((10, )).reshape((2, 5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981]])

In [10]:
np.random.seed(10)
np.random.randint(50, 80, (4, 3, 3))

array([[[59, 79, 54],
        [65, 50, 67],
        [77, 78, 75]],

       [[79, 66, 79],
        [67, 76, 58],
        [59, 50, 60]],

       [[58, 72, 54],
        [69, 66, 54],
        [65, 61, 72]],

       [[74, 61, 76],
        [51, 58, 54],
        [64, 67, 69]]])

In [11]:
np.random.randint(50, 80, (4, 3, 3)).flatten()

array([72, 63, 55, 63, 69, 75, 63, 78, 72, 75, 62, 51, 75, 54, 77, 68, 79,
       63, 72, 73, 74, 61, 78, 60, 74, 59, 65, 68, 66, 72, 57, 74, 61, 67,
       64, 57])

In [12]:
np.arange(30).reshape((3, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])