In [1]:
import numpy as np

In [2]:
first = np.array([[1, 2, 3], [4, 5, 6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
first.ndim

2

In [4]:
second = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
first + second

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [6]:
first + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [7]:
first - 1

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
first * 2 + 2

array([[ 4,  6,  8],
       [10, 12, 14]])

In [9]:
first / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])